# <center>**Build XGB Model**</center>  
**Author**: Shirshak Aryal  
**Last Updated**: 18 July 2025

---
**Purpose:** This notebook is dedicated to training and evaluating an XGBoost regression model for `pGI50` prediction. It covers loading pre-split data, optimizing hyperparameters using Optuna, training the final model with optimal parameters, and comprehensively evaluating its performance on unseen test data.

---

## 1. Setup Notebook
This section initializes the notebook environment by importing all necessary libraries, configuring system settings for performance, and defining global parameters and file paths.

### 1.1. Configure Environment
This section sets environment variables to optimize CPU core usage for numerical computations, which can significantly impact the performance of libraries like XGBoost.

In [1]:
# General CPU Usage Optimization
import os

os.environ["OMP_NUM_THREADS"] = "16"
os.environ["MKL_NUM_THREADS"] = "16"
os.environ["OPENBLAS_NUM_THREADS"] = "16"
os.environ["NUMEXPR_NUM_THREADS"] = "16"

### 1.2. Import Libraries
All required Python libraries for data manipulation, machine learning model building (XGBoost), hyperparameter optimization (Optuna), model evaluation (scikit-learn metrics), and utility functions are imported here.

In [2]:
# Standard Library Imports
from pathlib import Path
import subprocess  # For getting Git commit ID

# Core Data Science Libraries
import numpy as np
import pandas as pd

# Machine Learning Libraries
import joblib  # For saving/loading models
import optuna  # For hyperparameter optimization
import optuna.integration  # For Optuna's integrations (e.g., LightGBM, XGBoost callbacks)
from sklearn.metrics import mean_squared_error, r2_score  # For model evaluation metrics
import xgboost as xgb  # The XGBoost model library

# Conditional import for progress bars (tqdm)
tqdm_notebook_available = False  # Initialize flag
try:
    from tqdm.notebook import tqdm

    tqdm.pandas()  # Enable tqdm for pandas apply method
    tqdm_notebook_available = True
    print("tqdm.notebook found and enabled for pandas.")
except ImportError:
    print("tqdm.notebook not found. Install with 'pip install tqdm'.")

tqdm.notebook found and enabled for pandas.

### 1.3. Set Final Model Save Location

In [3]:
xgb_models_base_dir = Path("../models/xgb")
xgb_models_base_dir.mkdir(parents=True, exist_ok=True)
print(f"The final XGBoost model will be saved in: {xgb_models_base_dir}")

The final XGBoost model will be saved in: ..\models\xgb

## 2. Load Data Splits
This section loads the pre-engineered and split datasets (training, validation, and test sets for both features and target variable) that were prepared in the previous notebook.

In [12]:
splits_dir = Path("../data/splits")
print(f"\nLoading data splits from {splits_dir}...")

try:
    X_train = pd.read_parquet(splits_dir / "X_train_refined.parquet")
    X_val = pd.read_parquet(splits_dir / "X_val_refined.parquet")
    X_test = pd.read_parquet(splits_dir / "X_test_refined.parquet")

    y_train = pd.read_parquet(splits_dir / "y_train_refined.parquet")
    y_val = pd.read_parquet(splits_dir / "y_val_refined.parquet")
    y_test = pd.read_parquet(splits_dir / "y_test_refined.parquet")
    print("Data splits loaded successfully.")

    # Check the data splitting metadata commit hash
    ds_metadata_filename = splits_dir / "data_splitting_metadata.parquet"
    ds_metadata_df = pd.read_parquet(ds_metadata_filename)
    ds_commit_hash = ds_metadata_df["creation_commit_hash"].iloc[0]
    ds_timestamp = ds_metadata_df["creation_timestamp"].iloc[0]

    print("\n--- Data Splitting Traceability ---")
    print(f"Data Origin (DS Commit Hash): {ds_commit_hash}")
    print(f"Data Creation Timestamp:      {ds_timestamp}")
    print("--------------------------------------")
except FileNotFoundError:
    print(f"Error: One or more split files not found in '{splits_dir}'.")
    print("Please ensure you have run '02_Split_Features.ipynb' to generate and save the splits.")

print(f"X_train shape: {X_train.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"X_test shape: {X_test.shape}")

print(f"y_train shape: {y_train.shape}")
print(f"y_val shape: {y_val.shape}")
print(f"y_test shape: {y_test.shape}")

# Display first few rows to verify data
print("\nFirst 5 rows of X_train:")
display(X_train.head())

print("\nFirst 5 rows of y_train:")
display(y_train.head())

Loading data splits from ..\data\splits...
Data splits loaded successfully.

--- Data Splitting Traceability ---
Data Origin (DS Commit Hash): 14773e4
Data Creation Timestamp:      2025-10-21T02:26:20.503578
--------------------------------------
X_train shape: (13144, 2195)
X_val shape: (2817, 2195)
X_test shape: (2817, 2195)
y_train shape: (13144, 1)
y_val shape: (2817, 1)
y_test shape: (2817, 1)

First 5 rows of X_train:

,molregno,canonical_smiles,num_activities,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,MaxPartialCharge,MinPartialCharge,...,morgan_fp_2038,morgan_fp_2039,morgan_fp_2040,morgan_fp_2041,morgan_fp_2042,morgan_fp_2043,morgan_fp_2044,morgan_fp_2045,morgan_fp_2046,morgan_fp_2047
0,1589286,Cc1cc(Cn2ccnc2)c2ccc3[nH]ccc3c2n1,5,0.815267,0.815267,0.602362,11.450000,262.316,0.094856,-0.361111,...,0,0,0,0,0,0,0,0,0,0
1,2501077,O=C(COc1ccc(/C=C2\SC(=O)NC2=O)cc1)Nc1cccc([N+]...,2,0.125709,-0.548979,0.434119,14.642857,399.384,0.290425,-0.483773,...,0,0,0,0,0,0,1,0,0,0
2,2050773,CS(=O)(=O)N1CCN(C(=O)c2cccc(Nc3ncc(F)c(Nc4ccc(...,2,0.094794,-3.286588,0.549363,14.617647,488.520,0.253518,-0.337616,...,0,0,0,0,0,0,0,0,0,0
3,2227924,OCc1ccc(-c2ccc(-c3ccc(CO)o3)s2)o1,1,0.100916,-0.100916,0.767264,11.052632,276.313,0.143876,-0.457787,...,0,0,0,0,0,0,0,0,0,0
4,2225019,COc1cccc(NC(=S)N2N=C(c3cc(OC)c(OC)cc3O)CC2c2cc...,2,0.057031,-0.195181,0.300963,14.837838,513.619,0.194232,-0.507114,...,0,0,0,0,0,0,0,0,0,0

First 5 rows of y_train:

          pGI50
10070  4.322246
16307  4.460545
12174  4.802823
13288  6.886053
13241  4.638338

## 3. Prepare Data for XGBoost
This section performs final data preparation steps specifically required for the XGBoost model, including dropping identifier columns and converting data splits to NumPy arrays.

In [5]:
# Drop identifier columns which are not features for the model
print("\nPreparing X for XGBoost training (dropping identifiers)...")
X_train_xgb = X_train.drop(columns=['molregno', 'canonical_smiles'], errors='ignore')
X_val_xgb = X_val.drop(columns=['molregno', 'canonical_smiles'], errors='ignore')
X_test_xgb = X_test.drop(columns=['molregno', 'canonical_smiles'], errors='ignore')

print(f"X_train_xgb shape (numerical features only): {X_train_xgb.shape}")
print(f"X_val_xgb shape (numerical features only): {X_val_xgb.shape}")
print(f"X_test_xgb shape (numerical features only): {X_test_xgb.shape}")

display(X_train_xgb.head())
display(y_train.head())

print("Converting data to numpy arrays...")
# XGBoost typically works well with NumPy arrays
X_train_xgb = X_train_xgb.values.astype(np.float32)
y_train = y_train.values.astype(np.float32)

X_val_xgb = X_val_xgb.values.astype(np.float32)
y_val = y_val.values.astype(np.float32)

X_test_xgb = X_test_xgb.values.astype(np.float32)
y_test = y_test.values.astype(np.float32)

print(f"X_train_xgb type after conversion: {type(X_train_xgb)}")
print(f"X_train_xgb dtype: {X_train_xgb.dtype}")
print("\nData preparation for XGBoost complete. Ready for model definition and training.")

Preparing X for XGBoost training (dropping identifiers)...
X_train_xgb shape (numerical features only): (13144, 2193)
X_val_xgb shape (numerical features only): (2817, 2193)
X_test_xgb shape (numerical features only): (2817, 2193)

,num_activities,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,MaxPartialCharge,MinPartialCharge,FpDensityMorgan1,AvgIpc,...,morgan_fp_2038,morgan_fp_2039,morgan_fp_2040,morgan_fp_2041,morgan_fp_2042,morgan_fp_2043,morgan_fp_2044,morgan_fp_2045,morgan_fp_2046,morgan_fp_2047
0,5,0.815267,0.815267,0.602362,11.450000,262.316,0.094856,-0.361111,1.200000,3.080856,...,0,0,0,0,0,0,0,0,0,0
1,2,0.125709,-0.548979,0.434119,14.642857,399.384,0.290425,-0.483773,1.214286,2.980113,...,0,0,0,0,0,0,1,0,0,0
2,2,0.094794,-3.286588,0.549363,14.617647,488.520,0.253518,-0.337616,0.970588,2.817623,...,0,0,0,0,0,0,0,0,0,0
3,1,0.100916,-0.100916,0.767264,11.052632,276.313,0.143876,-0.457787,0.736842,3.163505,...,0,0,0,0,0,0,0,0,0,0
4,2,0.057031,-0.195181,0.300963,14.837838,513.619,0.194232,-0.507114,0.918919,3.374680,...,0,0,0,0,0,0,0,0,0,0

          pGI50
10070  4.322246
16307  4.460545
12174  4.802823
13288  6.886053
13241  4.638338

Converting data to numpy arrays...
X_train_xgb type after conversion: <class 'numpy.ndarray'>
X_train_xgb dtype: float32

Data preparation for XGBoost complete. Ready for model definition and training.

## 4. Optimize Hyperparameters
This section utilizes Optuna to systematically search for the optimal set of hyperparameters for the XGBoost model, aiming to minimize prediction error on the validation set.

### 4.1. Define Optuna Objective Function
The Optuna objective function is defined here. This function trains an XGBoost model with a given set of hyperparameters and returns its performance (e.g., RMSE) on the validation set, which Optuna aims to minimize.

In [6]:
def objective(trial):
    # Suggest these hyperparameters to Optuna.
    params = {
        'objective': 'reg:squarederror',  # Objective function (minimizes squared error)
        'eval_metric': 'rmse',  # Evaluation metric to be monitored during training (used for early stopping)
        'n_estimators': 5000, # Number of boosting rounds (trees)
        'learning_rate': trial.suggest_float("learning_rate", 0.001, 0.3, log=True),
        'max_depth': trial.suggest_int("max_depth", 3, 12), # Max depth of a tree
        'subsample': trial.suggest_float("subsample", 0.6, 1.0), # Subsample ratio of the training instance
        'colsample_bytree': trial.suggest_float("colsample_bytree", 0.6, 1.0), # Subsample ratio of columns when constructing each tree
        'reg_alpha': trial.suggest_float("reg_alpha", 1e-4, 1.0, log=True), # L1 regularization term
        'reg_lambda': trial.suggest_float("reg_lambda", 1e-4, 1.0, log=True), # L2 regularization term
        'gamma': trial.suggest_float("gamma", 1e-4, 1.0, log=True), # Minimum loss reduction required to make a further partition on a leaf node
        'min_child_weight': trial.suggest_int("min_child_weight", 1, 10), # Minimum sum of instance weight needed in a child
        'random_state': 42,  # Seed for reproducibility of model training (tree building)
        'tree_method': 'hist', # Use histogram-based algorithm for faster training
        'device': 'cuda:0',  # Specify to use GPU if available
        'early_stopping_rounds': 50,
    }

    # Initialize model with suggested hyperparams
    model = xgb.XGBRegressor(**params)

    # Ensure y_train and y_val are correctly shaped as 2D arrays if they are currently 1D
    # This prevents subtle CUDA/Numpy conflicts
    y_train_2d = y_train.reshape(-1, 1) if y_train.ndim == 1 else y_train
    y_val_2d = y_val.reshape(-1, 1) if y_val.ndim == 1 else y_val

    # Train model on training data, evaluating on validation set for early stopping
    try:
        model.fit(
            X_train_xgb, y_train_2d,
            eval_set=[(X_val_xgb, y_val_2d)], # Use the validation set for early stopping and pruning decisions
            verbose=False,
        )
    except xgb.core.XGBoostError as e:
        # Handle cases where specific hyperparameter combinations might lead to training errors
        print(f"XGBoost training error for trial {trial.number}: {e}")
        trial.set_user_attr("exception_type", "XGBoostError")
        trial.set_user_attr("exception_message", str(e))
        return float('inf') # Return a very high value (infinity) to Optuna to discourage this problematic trial

    except Exception as e:
        # Catch any other Python errors
        print(f"Trial {trial.number} failed due to General Error: {e}")
        return float('inf')

    if trial.should_prune():
        raise optuna.exceptions.TrialPruned()

    # Make predictions on validation set using the best booster from early stopping
    y_pred_val = model.predict(X_val_xgb)

    # Calculate RMSE and R2 score on validation set
    rmse = float(np.sqrt(mean_squared_error(y_val, y_pred_val)))
    r2 = float(r2_score(y_val, y_pred_val))

    trial.set_user_attr("r2_score", r2)  # Store R2 score as a user attribute for later inspection
    trial.set_user_attr("n_estimators_best", model.best_iteration)

    return rmse  # Optuna minimizes this RMSE value to find the best trial

### 4.2. Run Optuna Study
An Optuna study is created and executed to perform the hyperparameter optimization, iterating through trials to find the best combination of parameters.

In [7]:
optuna.logging.set_verbosity(optuna.logging.INFO) # Set Optuna logging level

print("Optuna logging verbosity set to INFO.")
# Define the path for the Optuna study database storage
study_dir = Path("../studies/xgboost_study")
study_dir.mkdir(parents=True, exist_ok=True)

study_db_path = f"sqlite:///{study_dir / 'xgb_optuna_study_refined.db'}"
study_name = "xgboost_regression_pGI50_refined"
print(f"Optuna study will be stored at: {study_db_path}")

# Check if a study with the same name already exists in the database
# If it does, load it to resume the optimization
try:
    study = optuna.load_study(study_name=study_name, storage=study_db_path)
    print(f"Loaded existing study '{study_name}' from {study_db_path}. Resuming optimization.")
except KeyError:
    # If the study does not exist, create a new one
    print(f"Creating new study '{study_name}' at {study_db_path}.")
    study = optuna.create_study(
        study_name=study_name,
        direction="minimize", # Minimize the RMSE
        storage=study_db_path,
    )

print("\nStarting Optuna optimization...")

# Run up to 300 trials or for 2 hours (7200 seconds)
study.optimize(objective, n_trials=300, timeout=7200, show_progress_bar=True)

print("\nOptuna optimization finished.")

# Print best trial results from the study
print("\n--- Best Trial Results ---")
print(f"Best trial number: {study.best_trial.number}")
print(f"Best RMSE (Validation): {study.best_value:.4f}")
print("Best hyperparameters:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

# Access and print the R2 score stored as a user attribute for the best trial
if "r2_score" in study.best_trial.user_attrs:
    print(f"Best R2 Score (Validation): {study.best_trial.user_attrs['r2_score']:.4f}")

Optuna logging verbosity set to INFO.
Optuna study will be stored at: sqlite:///..\studies\xgboost_study\xgb_optuna_study_refined.db
Loaded existing study 'xgboost_regression_pGI50_refined' from sqlite:///..\studies\xgboost_study\xgb_optuna_study_refined.db. Resuming optimization.

Starting Optuna optimization...

  0%|          | 0/300 [00:00<?, ?it/s]

c:\Users\Acer\Desktop\Projects for Data Science\Drug Gi50 Value Prediction\venv\Lib\site-packages\xgboost\core.py:729: UserWarning: [22:42:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

[I 2025-10-20 22:42:06,536] Trial 664 finished with value: 0.6153278824727346 and parameters: {'learning_rate': 0.19591696526858848, 'max_depth': 4, 'subsample': 0.8301141915626432, 'colsample_bytree': 0.7442712750322226, 'reg_alpha': 0.00010286296574071712, 'reg_lambda': 0.00029636054080102464, 'gamma': 0.3162326623593083, 'min_child_weight': 10}. Best is trial 664 with value: 0.6153278824727346.
[I 2025-10-20 22:42:13,307] Trial 665 finished with value: 0.6206959344100492 and parameters: {'learning_rate': 0.2155830539966202, 'max_depth': 3, 'subsample': 0.8384785916084286, 'colsample_bytree': 0.7419994429444048, 'reg_alpha': 0.00017159019619433758, 'reg_lambda': 0.00024010940593782054, 'gamma': 0.37859275955309385, 'min_child_weight': 10}. Best is trial 664 with value: 0.6153278824727346.
[I 2025-10-20 22:42:19,347] Trial 666 finished with value: 0.6179678848202673 and parameters: {'learning_rate': 0.2021321828830253, 'max_depth': 4, 'subsample': 0.8451770661914438, 'colsample_bytree': 0.7467384479715373, 'reg_alpha': 0.00010841102127564158, 'reg_lambda': 0.0003087058770471954, 'gamma': 0.28606333445257415, 'min_child_weight': 10}. Best is trial 664 with value: 0.6153278824727346.
[I 2025-10-20 22:42:25,301] Trial 667 finished with value: 0.6174996226614599 and parameters: {'learning_rate': 0.2059334103035865, 'max_depth': 4, 'subsample': 0.8319017991795722, 'colsample_bytree': 0.7412961262372502, 'reg_alpha': 0.0001551946827961855, 'reg_lambda': 0.00026385068985928286, 'gamma': 0.23672501062105483, 'min_child_weight': 10}. Best is trial 664 with value: 0.6153278824727346.
[I 2025-10-20 22:42:31,795] Trial 668 finished with value: 0.6251689444132374 and parameters: {'learning_rate': 0.20562782737710705, 'max_depth': 4, 'subsample': 0.8398399231754534, 'colsample_bytree': 0.7325045423467352, 'reg_alpha': 0.00010624803103908179, 'reg_lambda': 0.00022039534456320403, 'gamma': 0.2975403291474525, 'min_child_weight': 10}. Best is trial 664 with value: 0.6153278824727346.
[I 2025-10-20 22:42:38,532] Trial 669 finished with value: 0.6223197209467117 and parameters: {'learning_rate': 0.20119695791099582, 'max_depth': 4, 'subsample': 0.8343234757374254, 'colsample_bytree': 0.7430093255032264, 'reg_alpha': 0.00010115630255488629, 'reg_lambda': 0.000279714130826565, 'gamma': 0.2964627577931455, 'min_child_weight': 10}. Best is trial 664 with value: 0.6153278824727346.
[I 2025-10-20 22:42:44,059] Trial 670 finished with value: 0.619105726155015 and parameters: {'learning_rate': 0.2077133621505585, 'max_depth': 4, 'subsample': 0.8298653904358699, 'colsample_bytree': 0.7468194263407274, 'reg_alpha': 0.00010193077915783177, 'reg_lambda': 0.00024887594125908046, 'gamma': 0.25866290709002854, 'min_child_weight': 10}. Best is trial 664 with value: 0.6153278824727346.
[I 2025-10-20 22:42:51,947] Trial 671 finished with value: 0.6141920190941671 and parameters: {'learning_rate': 0.19368980218059853, 'max_depth': 4, 'subsample': 0.8331715204734833, 'colsample_bytree': 0.743325285448327, 'reg_alpha': 0.00011981327623759585, 'reg_lambda': 0.00028944307983323997, 'gamma': 0.2725054989609251, 'min_child_weight': 10}. Best is trial 671 with value: 0.6141920190941671.
[I 2025-10-20 22:43:01,048] Trial 672 finished with value: 0.6116784892468476 and parameters: {'learning_rate': 0.19103883665799012, 'max_depth': 4, 'subsample': 0.8445680446620872, 'colsample_bytree': 0.7456368574776324, 'reg_alpha': 0.00010042891715380902, 'reg_lambda': 0.0002754686136017416, 'gamma': 0.2951801398574685, 'min_child_weight': 10}. Best is trial 672 with value: 0.6116784892468476.
[I 2025-10-20 22:43:08,135] Trial 673 finished with value: 0.6191912849952078 and parameters: {'learning_rate': 0.19373731519855367, 'max_depth': 4, 'subsample': 0.8323950066814338, 'colsample_bytree': 0.7401799864616088, 'reg_alpha': 0.00010027896316706285, 'reg_lambda': 0.0002790135396914784, 'gamma': 0.2877234088651129, 'min_child_weight': 10}. Best is trial 672 with value: 0.6116784892468476.
[I 2025-10-20 22:43:18,372] Trial 674 finished with value: 0.6112306657319392 and parameters: {'learning_rate': 0.1891681495663571, 'max_depth': 4, 'subsample': 0.8401074839140934, 'colsample_bytree': 0.7432714710369887, 'reg_alpha': 0.00010057567574840683, 'reg_lambda': 0.0002742433303833323, 'gamma': 0.28648687869249784, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:43:24,209] Trial 675 finished with value: 0.6229038612512444 and parameters: {'learning_rate': 0.19151069588454173, 'max_depth': 4, 'subsample': 0.8360540650443443, 'colsample_bytree': 0.7472242064843121, 'reg_alpha': 0.00010096035380279921, 'reg_lambda': 0.0002565030232719998, 'gamma': 0.27697100910586253, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:43:31,387] Trial 676 finished with value: 0.6168164695250994 and parameters: {'learning_rate': 0.18212460277612869, 'max_depth': 4, 'subsample': 0.8342095338673883, 'colsample_bytree': 0.7427293331453967, 'reg_alpha': 0.00010032675272066508, 'reg_lambda': 0.00028381626969520437, 'gamma': 0.31369471729103365, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:43:38,412] Trial 677 finished with value: 0.6194495504417823 and parameters: {'learning_rate': 0.18091729380412092, 'max_depth': 4, 'subsample': 0.8323480106848901, 'colsample_bytree': 0.7432046686180851, 'reg_alpha': 0.00010252738782055994, 'reg_lambda': 0.0002640114938006611, 'gamma': 0.30321334568871605, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:43:44,644] Trial 678 finished with value: 0.626484466982767 and parameters: {'learning_rate': 0.1883964373982267, 'max_depth': 4, 'subsample': 0.8327492839681827, 'colsample_bytree': 0.744709602330047, 'reg_alpha': 0.00010076247901353013, 'reg_lambda': 0.00027772296292799764, 'gamma': 0.29659707607819435, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:43:52,284] Trial 679 finished with value: 0.6173600305772595 and parameters: {'learning_rate': 0.18830527243293926, 'max_depth': 4, 'subsample': 0.8313935678257138, 'colsample_bytree': 0.7459074816010671, 'reg_alpha': 0.00010017010312243165, 'reg_lambda': 0.0003125784147199865, 'gamma': 0.30124135277188224, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:43:58,771] Trial 680 finished with value: 0.6253763734526786 and parameters: {'learning_rate': 0.18325061241479948, 'max_depth': 4, 'subsample': 0.8344247736401781, 'colsample_bytree': 0.7432265393152487, 'reg_alpha': 0.0001042465277827188, 'reg_lambda': 0.0002703522389444394, 'gamma': 0.304796002020203, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:06,465] Trial 681 finished with value: 0.6214305756094988 and parameters: {'learning_rate': 0.19244794851403194, 'max_depth': 4, 'subsample': 0.8318877841507905, 'colsample_bytree': 0.743923872439668, 'reg_alpha': 0.0001016894073374415, 'reg_lambda': 0.00026293617132349274, 'gamma': 0.29700699365917904, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:13,707] Trial 682 finished with value: 0.6218370512305302 and parameters: {'learning_rate': 0.1967500153357014, 'max_depth': 4, 'subsample': 0.8338055970542669, 'colsample_bytree': 0.7444493930456512, 'reg_alpha': 0.00010010495480871669, 'reg_lambda': 0.00027424179105143003, 'gamma': 0.3153502391879938, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:21,205] Trial 683 finished with value: 0.6209790585744815 and parameters: {'learning_rate': 0.19057089312801953, 'max_depth': 4, 'subsample': 0.8344206008977496, 'colsample_bytree': 0.7440523512521097, 'reg_alpha': 0.0001001516488103965, 'reg_lambda': 0.0002616233780796606, 'gamma': 0.3044437397921307, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:28,926] Trial 684 finished with value: 0.6247669262220774 and parameters: {'learning_rate': 0.19058009867196568, 'max_depth': 4, 'subsample': 0.832192898099808, 'colsample_bytree': 0.7455632116202933, 'reg_alpha': 0.00010017910195054512, 'reg_lambda': 0.00026413402607858576, 'gamma': 0.30304964377708327, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:37,101] Trial 685 finished with value: 0.6198659793530485 and parameters: {'learning_rate': 0.18887589943255562, 'max_depth': 4, 'subsample': 0.8326168564210055, 'colsample_bytree': 0.7465316944385878, 'reg_alpha': 0.00010438204364606015, 'reg_lambda': 0.00027520803759485305, 'gamma': 0.2983394715414628, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:43,489] Trial 686 finished with value: 0.6197019854077502 and parameters: {'learning_rate': 0.17998588019602488, 'max_depth': 4, 'subsample': 0.8337230521627225, 'colsample_bytree': 0.7459812066651111, 'reg_alpha': 0.00010228672753535263, 'reg_lambda': 0.00026922937952790927, 'gamma': 0.32145294399506497, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:49,341] Trial 687 finished with value: 0.622720806455928 and parameters: {'learning_rate': 0.19411041748870742, 'max_depth': 4, 'subsample': 0.8311057454456913, 'colsample_bytree': 0.7446494542218367, 'reg_alpha': 0.00010093054693130432, 'reg_lambda': 0.00027194043625846097, 'gamma': 0.30159073383943374, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:44:58,071] Trial 688 finished with value: 0.6270718566080881 and parameters: {'learning_rate': 0.18853049555931292, 'max_depth': 4, 'subsample': 0.831173960964058, 'colsample_bytree': 0.7431696688324569, 'reg_alpha': 0.00010330229508768414, 'reg_lambda': 0.0002683155402807696, 'gamma': 0.29100694384181375, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:45:06,780] Trial 689 finished with value: 0.620520032859014 and parameters: {'learning_rate': 0.19164891617495095, 'max_depth': 4, 'subsample': 0.8323674943598098, 'colsample_bytree': 0.7435428278250095, 'reg_alpha': 0.00010189244414022886, 'reg_lambda': 0.0002735069602703615, 'gamma': 0.31118048458635295, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:45:14,258] Trial 690 finished with value: 0.6205481766157969 and parameters: {'learning_rate': 0.17178501581768055, 'max_depth': 4, 'subsample': 0.8363843590688396, 'colsample_bytree': 0.747897487305368, 'reg_alpha': 0.00010017933039502592, 'reg_lambda': 0.0002923974777212586, 'gamma': 0.28035085614648186, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:45:18,652] Trial 691 finished with value: 0.6266717487325282 and parameters: {'learning_rate': 0.16910367062407408, 'max_depth': 4, 'subsample': 0.8379364263103595, 'colsample_bytree': 0.7502271952261449, 'reg_alpha': 0.00010466480087051463, 'reg_lambda': 0.0003132903724295353, 'gamma': 0.33931034690149686, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:45:23,390] Trial 692 finished with value: 0.6347271716868356 and parameters: {'learning_rate': 0.20213102714497236, 'max_depth': 4, 'subsample': 0.8261893832831697, 'colsample_bytree': 0.7409733811766002, 'reg_alpha': 0.00011571753592891236, 'reg_lambda': 0.00020870223786775466, 'gamma': 0.2910342442630963, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:45:30,123] Trial 693 finished with value: 0.6152387588586994 and parameters: {'learning_rate': 0.16800592679142523, 'max_depth': 4, 'subsample': 0.8370366502538306, 'colsample_bytree': 0.7482387357078691, 'reg_alpha': 0.00010228955131396126, 'reg_lambda': 0.0002529755615772704, 'gamma': 0.2461623466268574, 'min_child_weight': 10}. Best is trial 674 with value: 0.6112306657319392.
[I 2025-10-20 22:45:37,939] Trial 694 finished with value: 0.6110425775804915 and parameters: {'learning_rate': 0.15645879177993313, 'max_depth': 4, 'subsample': 0.844287260756954, 'colsample_bytree': 0.7503875154030433, 'reg_alpha': 0.00010041007962319547, 'reg_lambda': 0.0003496622983820379, 'gamma': 0.24715803790179083, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:45:45,123] Trial 695 finished with value: 0.6212905236196741 and parameters: {'learning_rate': 0.17423483511777973, 'max_depth': 4, 'subsample': 0.8457440673298261, 'colsample_bytree': 0.7513065985785317, 'reg_alpha': 0.00010068494536471517, 'reg_lambda': 0.0003708849490417962, 'gamma': 0.24970388789031253, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:45:52,503] Trial 696 finished with value: 0.6224752213245931 and parameters: {'learning_rate': 0.1714918706139426, 'max_depth': 4, 'subsample': 0.8457345797421709, 'colsample_bytree': 0.753115894520571, 'reg_alpha': 0.00012113332358583602, 'reg_lambda': 0.0003584554022015217, 'gamma': 0.23968882048078657, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:46:02,350] Trial 697 finished with value: 0.6131100992847744 and parameters: {'learning_rate': 0.15503663315085747, 'max_depth': 4, 'subsample': 0.8462511481143105, 'colsample_bytree': 0.7540864023380883, 'reg_alpha': 0.00012355115641246063, 'reg_lambda': 0.0003578008294455569, 'gamma': 0.24325120941161132, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:46:11,531] Trial 698 finished with value: 0.614873338154631 and parameters: {'learning_rate': 0.15537768767068397, 'max_depth': 4, 'subsample': 0.8454032305165832, 'colsample_bytree': 0.7561409242875631, 'reg_alpha': 0.00012531068503762323, 'reg_lambda': 0.0003481500073219167, 'gamma': 0.2309548817824412, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:46:19,768] Trial 699 finished with value: 0.6131572719561764 and parameters: {'learning_rate': 0.1572134519109709, 'max_depth': 4, 'subsample': 0.8466530923431086, 'colsample_bytree': 0.7561188551270778, 'reg_alpha': 0.00012395600518502612, 'reg_lambda': 0.00040393132015240004, 'gamma': 0.2379794169808701, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:46:29,043] Trial 700 finished with value: 0.6146179986864908 and parameters: {'learning_rate': 0.15094258575591632, 'max_depth': 4, 'subsample': 0.8431425774325404, 'colsample_bytree': 0.7553055457523506, 'reg_alpha': 0.00012634803584096207, 'reg_lambda': 0.00038935496395260324, 'gamma': 0.22930652943333052, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:46:37,760] Trial 701 finished with value: 0.6131874304279431 and parameters: {'learning_rate': 0.15271891153233438, 'max_depth': 4, 'subsample': 0.8478605806443649, 'colsample_bytree': 0.7549483830062482, 'reg_alpha': 0.00012395857777933704, 'reg_lambda': 0.0004129831177369627, 'gamma': 0.23707499183279088, 'min_child_weight': 10}. Best is trial 694 with value: 0.6110425775804915.
[I 2025-10-20 22:46:46,886] Trial 702 finished with value: 0.6105218268373749 and parameters: {'learning_rate': 0.15365451110638625, 'max_depth': 4, 'subsample': 0.8472787491686126, 'colsample_bytree': 0.7559564140580186, 'reg_alpha': 0.00012942513950781444, 'reg_lambda': 0.0003972027750489074, 'gamma': 0.22854018391194045, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:46:54,163] Trial 703 finished with value: 0.6170348207936021 and parameters: {'learning_rate': 0.1492897717346392, 'max_depth': 4, 'subsample': 0.8490530746083308, 'colsample_bytree': 0.7578841343453805, 'reg_alpha': 0.00012895347276857143, 'reg_lambda': 0.0004042041409164123, 'gamma': 0.22026792139868676, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:47:01,677] Trial 704 finished with value: 0.6168761614911277 and parameters: {'learning_rate': 0.14978785487239304, 'max_depth': 4, 'subsample': 0.8495214988311952, 'colsample_bytree': 0.7584379550152052, 'reg_alpha': 0.00012962033712019108, 'reg_lambda': 0.0004296227009731827, 'gamma': 0.23547254683628116, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:47:11,082] Trial 705 finished with value: 0.6210538023571605 and parameters: {'learning_rate': 0.15375956856605544, 'max_depth': 4, 'subsample': 0.8507790142841499, 'colsample_bytree': 0.756153689247791, 'reg_alpha': 0.00012946621024082994, 'reg_lambda': 0.00041078243695847325, 'gamma': 0.23727816242393268, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:47:20,470] Trial 706 finished with value: 0.6172461662899593 and parameters: {'learning_rate': 0.14487999045908528, 'max_depth': 4, 'subsample': 0.8470255177143722, 'colsample_bytree': 0.7580630034027959, 'reg_alpha': 0.0001286352738930841, 'reg_lambda': 0.0003282820071035363, 'gamma': 0.20913395064453877, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:47:29,854] Trial 707 finished with value: 0.6136710027910683 and parameters: {'learning_rate': 0.14626488156869455, 'max_depth': 4, 'subsample': 0.8470835293960588, 'colsample_bytree': 0.7574675445912555, 'reg_alpha': 0.00013032220921049297, 'reg_lambda': 0.000408501793120013, 'gamma': 0.21918785168388613, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:47:37,732] Trial 708 finished with value: 0.6134227176465068 and parameters: {'learning_rate': 0.1473927666646926, 'max_depth': 4, 'subsample': 0.846848545359739, 'colsample_bytree': 0.7593037181583984, 'reg_alpha': 0.00013231301949229244, 'reg_lambda': 0.0004077832594815902, 'gamma': 0.20277829814045617, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:47:43,079] Trial 709 finished with value: 0.6254978342986941 and parameters: {'learning_rate': 0.14374838194375067, 'max_depth': 4, 'subsample': 0.8504021705917885, 'colsample_bytree': 0.7588419942173219, 'reg_alpha': 0.00013393997245712605, 'reg_lambda': 0.00042730677229665937, 'gamma': 0.20336294262086885, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:47:51,063] Trial 710 finished with value: 0.6139487017922494 and parameters: {'learning_rate': 0.15166923331300025, 'max_depth': 4, 'subsample': 0.8476444289474934, 'colsample_bytree': 0.759819754515532, 'reg_alpha': 0.00013301716517930877, 'reg_lambda': 0.0003478851912133161, 'gamma': 0.21223079171425352, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:48:00,811] Trial 711 finished with value: 0.6158744026043369 and parameters: {'learning_rate': 0.1519825444884886, 'max_depth': 4, 'subsample': 0.8499004255148318, 'colsample_bytree': 0.7607263922210539, 'reg_alpha': 0.00013523112457783162, 'reg_lambda': 0.0003454005164443351, 'gamma': 0.21015066897617862, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.
[I 2025-10-20 22:48:09,614] Trial 712 finished with value: 0.6131662637588796 and parameters: {'learning_rate': 0.15275989434422804, 'max_depth': 4, 'subsample': 0.8526000875883661, 'colsample_bytree': 0.7607130012137113, 'reg_alpha': 0.00013407551685559545, 'reg_lambda': 0.0003418126791853744, 'gamma': 0.20144250942281486, 'min_child_weight': 10}. Best is trial 702 with value: 0.6105218268373749.

## 5. Train Final Model
This section trains the final XGBoost model using the best hyperparameters identified by Optuna and saves it for future use.

### 5.1. Reinitialize Model with Best Hyperparameters
The XGBoost model is reinitialized using the optimal hyperparameters found during the Optuna study.

In [8]:
# Re-load the study to ensure the latest best parameters
study_dir = Path("../studies/xgboost_study")
study_db_path = f"sqlite:///{study_dir / 'xgb_optuna_study_refined.db'}"
study_name = "xgboost_regression_pGI50_refined"

try:
    study = optuna.load_study(study_name=study_name, storage=study_db_path)
    best_trial = study.best_trial
    best_params = best_trial.params
    best_n_estimators = best_trial.user_attrs.get("n_estimators_best")

    print("--- Loaded Best Trial Data ---")
    print(f"Best RMSE (Validation): {study.best_value:.4f}")
    print(f"Optimized n_estimators (Best Iteration): {best_n_estimators}")
    print("Base hyperparameters:", best_params)
except KeyError:
    print("Study does not exist. Please make sure that the previous Optuna study cell has been run.")

# Add fixed parameters that were not part of Optuna's search but are required for the model
best_params["n_estimators"] = best_n_estimators
best_params['objective'] = 'reg:squarederror' # Objective function for regression
best_params['eval_metric'] = 'rmse' # Evaluation metric
best_params['random_state'] = 42 # For reproducibility of the final model
best_params['tree_method'] = 'hist' # Histogram-based method for efficiency
best_params['device'] = 'cuda:0' # Set device for final training ('cuda:0' for GPU, 'cpu' for CPU)

# Initialize the final XGBoost model with the best parameters found by Optuna
final_xgb_model = xgb.XGBRegressor(**best_params)
print("Final model has been initialized with best parameters. Ready for training.")

--- Loaded Best Trial Data ---
Best RMSE (Validation): 0.5915
Optimized n_estimators (Best Iteration): 4405
Base hyperparameters: {'learning_rate': 0.035852762830664464, 'max_depth': 5, 'subsample': 0.9495734596109369, 'colsample_bytree': 0.8341043325804682, 'reg_alpha': 0.001044582788012534, 'reg_lambda': 0.005906794482974822, 'gamma': 0.029957788076497214, 'min_child_weight': 9}
Final model has been initialized with best parameters. Ready for training.

### 5.2. Get Current Git Commit ID
The current Git commit ID (hash) is programmatically retrieved. This commit ID will be saved as essential metadata to ensure direct traceability and reproducibility.

In [13]:
def get_git_commit_hash():
    try:
        # Get the short commit hash
        commit_hash = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).strip().decode('ascii')
        return commit_hash
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown_commit"

In [14]:
# Optionally, see the current commit ID
current_commit = get_git_commit_hash()
print(f"Current Git Commit ID: {current_commit}")

Current Git Commit ID: 38344cb

### 5.3. Train and Save Model
The final XGBoost model is trained on the combined training and validation datasets and then saved locally along with essential metadata.

In [ ]:
# TRAIN FINAL MODEL
print("\nTraining final XGBoost model on the full training set (combined original training data + original validation data)...")

# Concatenate the original training and validation data for final model training
X_train_xgb_final = np.concatenate([X_train_xgb, X_val_xgb]).astype(np.float32)
y_train_xgb_final = np.concatenate([y_train, y_val]).astype(np.float32)

# Train the model
# No early stopping here as training is done on combined set (hence no separate validation set).
final_xgb_model.fit(X_train_xgb_final, y_train_xgb_final, verbose=False)
print("Final model training complete. Ready for test set evaluation.")


# SAVE FINAL MODEL WITH METADATA
# Prepare model metadata dictionary
FINAL_MODEL_FEATURE_SCHEMA = list(X_train.columns)
FINAL_MODEL_COMMIT_HASH = get_git_commit_hash()
DATA_SOURCE_COMMIT_HASH = ds_commit_hash
FINAL_MODEL_BEST_HYPERPARAMS = best_params
BEST_OPTUNA_VAL_RMSE = study.best_value

metadata_dict = {
    'final_model_object': final_xgb_model,
    'feature_schema': FINAL_MODEL_FEATURE_SCHEMA,
    'best_hyperparams': FINAL_MODEL_BEST_HYPERPARAMS,
    'best_val_rmse': BEST_OPTUNA_VAL_RMSE,
    'code_commit_hash': FINAL_MODEL_COMMIT_HASH,
    'data_source_commit_hash': DATA_SOURCE_COMMIT_HASH,
}

metadata_filename = Path(f'final_best_xgboost_model_metadata.joblib')

# Directory to save the model
save_dir = Path('../models/xgb')
save_dir.mkdir(parents=True, exist_ok=True)

full_path = save_dir / metadata_filename

print(f"\nSaving the final XGBoost Model Metadata Dictionary to: {full_path}...")
try:
    # We save the dictionary itself, making one self-describing file.
    joblib.dump(metadata_dict, full_path)
    print("Final Model Metadata Dictionary saved successfully!")
    print(
        f"XGB Code Hash: {FINAL_MODEL_COMMIT_HASH} | Data Source Commit Hash: {DATA_SOURCE_COMMIT_HASH}"
    )
except Exception as e:
    print(f"Error saving model contract: {e}")

Training final XGBoost model on the full training set (combined original training data + original validation data)...
Final model training complete. Ready for test set evaluation.

Saving the final XGBoost Model Metadata Dictionary to: ..\models\xgb\final_best_xgboost_model_metadata.joblib...
Final Model Metadata Dictionary saved successfully!
XGB Code Hash: 38344cb | Data Source Commit Hash: 14773e4

## 6. Evaluate Model
This section performs a final, unbiased evaluation of the trained XGBoost model's performance on the previously unseen test dataset.

In [17]:
# Load the final xgboost model
path_to_metadata_file = xgb_models_base_dir / metadata_filename

print(f"Loading final saved model metadata from '{metadata_filename}'...")
try:
    final_xgb_model_metadata = joblib.load(path_to_metadata_file)
except FileNotFoundError:
    print(f"FATAL ERROR: Model metadata file not found at {path_to_metadata_file}.")

# Extract components from the metadata
expected_schema = final_xgb_model_metadata["feature_schema"]
final_xgb_model = final_xgb_model_metadata["final_model_object"]
data_source_hash = final_xgb_model_metadata["data_source_commit_hash"]
code_commit_hash = final_xgb_model_metadata["code_commit_hash"]
best_val_rmse = final_xgb_model_metadata["best_val_rmse"]

# Check if the data schema is compatible
current_test_schema = list(X_test.columns)
print("Checking data schema compatibility...")
if expected_schema != current_test_schema:
    error_msg = (
        "\n!!! DATA SCHEMA MISMATCH DETECTED !!!\n"
        f"This model (Code: {code_commit_hash}) was trained on {len(expected_schema)} features, "
        f"but the current test data has {len(current_test_schema)} features.\n"
        f"Data Origin (Data Splitting Commit): {data_source_hash}\n"
        "ACTION REQUIRED: Please either retrain the model or check the feature engineering code."
    )
    raise RuntimeError(error_msg)

print(f"Schema check passed. {len(current_test_schema)} features match the model's expectations.")


# Make predictions and evaluate model
print("Making predictions and evaluating on the test set...")

# Set device to 'cpu' for prediction to prevent potential device
# mismatch errors if the model was trained on GPU
final_xgb_model.set_params(device='cuda:0')
y_pred_test_xgb = final_xgb_model.predict(X_test_xgb)

# Calculate final RMSE and R2 score on the test set
rmse_test_xgb = np.sqrt(mean_squared_error(y_test, y_pred_test_xgb))
r2_test_xgb = r2_score(y_test, y_pred_test_xgb)

print(f"\n--- Final XGBoost Model Performance on Test Set ---")
print(f"Test RMSE: {rmse_test_xgb:.4f}")
print(f"Test R2 Score: {r2_test_xgb:.4f}")
print("---------------------------------------------------")
print(f"Model Trained Code Hash: {code_commit_hash}")
print(f"Data Source Code Hash: {data_source_hash}")
print(f"Optuna Validation RMSE (Baseline): {best_val_rmse:.4f}")

Loading final saved model metadata from 'final_best_xgboost_model_metadata.joblib'...
Checking data schema compatibility...
Schema check passed. 2195 features match the model's expectations.
Making predictions and evaluating on the test set...

--- Final XGBoost Model Performance on Test Set ---
Test RMSE: 0.5781
Test R2 Score: 0.6575
---------------------------------------------------
Model Trained Code Hash: 38344cb
Data Source Code Hash: 14773e4
Optuna Validation RMSE (Baseline): 0.5915